name: Lint

on:
  push:

jobs:
  run-flake8:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#       - name: Lint
#         run: |
#           pip install flake8
#           flake8 --verbose .
#       - name: Run flake8
#         uses: suo/flake8-github-action@releases/v1
#         with:
#           checkName: 'run-flake8'   # NOTE: this needs to be the same as the job name
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: flake8 Lint
        uses: py-actions/flake8@v2
