name: Flake8

on:
  push:

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#       - name: Lint
#         run: |
#           pip install flake8
#           flake8 --verbose .
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: flake8 Lint
        uses: py-actions/flake8@v2
