name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: rbialon/flake8-annotations@v1
      - uses: py-actions/flake8@v2
