name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
        poetry-version: [1.4.1]

    steps:
      - uses: actions/checkout@v3

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/artifacts
            ~/.cache/pypoetry/cache
          key: ${{ runner.os }}-pip
          # key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: poetry install

      - name: Test
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: make cover
